env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: nancy
    github:
      owner: sonatype-nexus-community
      name: homebrew-tap
    folder: Formula
    homepage: https://gonancy.dev
    description: Tool to check for vulnerabilities in Go dependencies
    test: system "#{bin}/nancy -v"
